apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: main-hpa
  namespace: frontend
spec:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: main-web
