apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: main-pvc
  namespace: frontend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
